import os

def load_msbe_neighbors(file_path, user_map, item_map, interaction_mat=None, sim_threshold=0.1):
    """
    Load Biclique Neighbors from file (Generated by MSBE).
    Format: u1 u2 ... | i1 i2 ...
    """
    user_neighbors = {}
    item_neighbors = {}
    
    print(f"Loading bicliques from {file_path}...")
    
    if os.path.exists(file_path):
        with open(file_path, 'r') as f:
            for line in f:
                parts = line.strip().split('|')
                if len(parts) < 2: continue
                
                # Parse User IDs
                us = []
                for u_str in parts[0].split():
                    if u_str in user_map:
                        us.append(user_map[u_str])
                
                # Parse Item IDs
                is_ = []
                for i_str in parts[1].split():
                    if i_str in item_map:
                        is_.append(item_map[i_str])
                
                # Build Neighborhoods (Clique Expansion)
                # Users in the same biclique are structural neighbors
                if len(us) > 1:
                    for u in us:
                        if u not in user_neighbors: user_neighbors[u] = []
                        # Add others as neighbors
                        user_neighbors[u].extend([x for x in us if x != u])
                        
                if len(is_) > 1:
                    for i in is_:
                        if i not in item_neighbors: item_neighbors[i] = []
                        item_neighbors[i].extend([x for x in is_ if x != i])
                        
    # Deduplicate and basic stats
    u_c = 0
    for k in user_neighbors:
        user_neighbors[k] = list(set(user_neighbors[k]))
        u_c += 1
        
    i_c = 0
    for k in item_neighbors:
        item_neighbors[k] = list(set(item_neighbors[k]))
        i_c += 1
        
    print(f"Loaded neighbors for {u_c} users and {i_c} items form Bicliques.")
    return user_neighbors, item_neighbors
